[tool.poetry]
name = "d_lab"
version = "0.1.0"
description = "深度学习实验室"
authors = ["good-as-water <790990241@qq.com>"]

[tool.poetry.dependencies]
python = "^3.7"
torch = "^1.10.2"
pytorch-lightning = "^1.5.10"
transformers = "^4.16.2"
datasets = "^1.18.3"
oss2 = "^2.15.0"
spacy = "^3.2.2"
hydra-core = "^1.1.1"
hydra-colorlog = "^1.1.0"
hydra-optuna-sweeper = "^1.1.2"
scikit-learn = "^1.0.2"
jieba = "^0.42.1"
wandb = "^0.12.10"
rich = "^12.0.0"
tqdm = "^4.63.0"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."spacy_factories"]
"sent_spancat" = "d_lab.spacy_components:make_spancat"

[tool.poetry.scripts]
d-lab = "d_lab.run:train"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# 添加清华镜像
[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true