_target_: nlhappy.datamodules.EventExtractionDataModule
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}

dataset: 
batch_size: 
plm: hfl/chinese-roberta-wwm-ext
auto_length: max
transform: sparse-gplinker
pin_memory: True
num_workers: 4