_target_: nlhappy.datamodules.EventExtractionDataModule
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}

dataset: 
batch_size: 
plm: hfl/chinese-roberta-wwm-ext
auto_length: max
transform: event-role-head-tail
pin_memory: False
num_workers: 0