_target_: nlhappy.datamodules.PromptSpanExtractionDataModule
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}


dataset: 
plm: hfl/chinese-roberta-wwm-ext
batch_size: 
max_length: -1
transform: global_span
pin_memory: False
num_workers: 0