_target_: nlhappy.datamodules.RelationExtractionDataModule

dataset: 
batch_size: 
transform: gplinker
plm: hfl/chinese-roberta-wwm-ext
auto_length: max
pin_memory: False
num_workers: 0
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}