_target_: nlhappy.datamodules.RelationExtractionDataModule

dataset: 
batch_size: 
transform: gplinker
plm: roberta-wwm-base
max_length: -1
pin_memory: False
num_workers: 0
dataset_dir: ${dataset_dir}
plm_dir: ${plm_dir}