_target_: nlhappy.datamodules.TextPairRegressionDataModule
dataset_dir: ${dataset_dir} 
plm_dir: ${plm_dir}

dataset: 
plm: hfl/chinese-roberta-wwm-ext
auto_length: max
batch_size:
num_workers: 0
pin_memory: False