_target_: d_lab.datamodules.SpanClassificationDataModule


dataset: clue_ner_charspan
pretrained_model: chinese-roberta-wwm-ext
max_length: 256
batch_size: 16
pin_memory: True
num_workers: 10
data_dir: ${data_dir}
pretrained_dir: ${pretrained_dir}
