_target_: d_lab.datamodules.SpanClassificationDataModule


dataset: 
max_length: 
batch_size:
plm: chinese-macbert-base 
pin_memory: True
num_workers: 10
data_dir: ${data_dir}
pretrained_dir: ${pretrained_dir}
