_target_: d_lab.datamodules.TextClassificationDataModule

dataset: cblue_tc_single
pretrained_model: chinese-roberta-wwm-ext
max_length: 350
is_multi_label: False
batch_size: 16
num_workers: 10
pin_memory: True
data_dir: ${data_dir} 
pretrained_dir: ${pretrained_dir}

