_target_: d_lab.datamodules.TokenClassificationDataModule

dataset: clue_ner_chartoken
pretrained_model: chinese-roberta-wwm-ext
max_length: 52
batch_size: 32
pin_memory: True
num_workers: 10
label_pad_id: -100
data_dir: ${data_dir}
pretrained_dir: ${pretrained_dir}
