_target_: d_lab.datamodules.TripleExtractionDataModule

dataset: 
max_length: 
batch_size: 
pretrained_model: chinese-roberta-wwm-ext
pin_memory: True
num_workers: 10
data_dir: ${data_dir}
pretrained_dir: ${pretrained_dir}