_target_: src.datamodules.sentence_pair_datamodule.SentencePairDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
data_name: lcqmc
batch_size: 32
tokenizer_name: bert-base-chinese
num_workers: 20
pin_memory: True
sentence_max_length: 64
return_sentence_pair: False