_target_: src.datamodules.SpanClassificationDataModule


dataset: clue_ner_span
pretrained_model: chinese-roberta-wwm-ext
max_length: 52
batch_size: 32
pin_memory: True
num_workers: 10
data_dir: ${data_dir}
pretrained_dir: ${pretrained_dir}