_target_: src.datamodules.TextClassificationDataModule
data_dir: ${data_dir} 
data_name: sent
train_val_test_split: [0.8, 0.1, 0.1]
text_max_length: 200
is_multi_label: False
batch_size: 16
num_workers: 10
pin_memory: True
tokenizer_name: bert-base-chinese
